export const characterLabel: Record<string, string> = {
  "first_job": "1ª Classe",
  "second_job": "2ª Classe",
  "third_job": "3ª Classe",
  "forth_job": "4ª Classe",
  "elesis_first_job": "Espadachim",
  "elesis_second_job": "Cavaleira",
  "elesis_third_job": "Gladiadora",
  "elesis_forth_job": "justiceira",
  "lire_first_job": "Arqueira",
  "lire_second_job": "Caçadora",
  "lire_third_job": "Guardiã",
  "lire_forth_job": "Nova",
  "arme_first_job": "Maga",
  "arme_second_job": "Alquimista",
  "arme_third_job": "Feiticeira",
  "arme_forth_job": "Arquimaga",
  "lass_first_job": "Ninja",
  "lass_second_job": "Mercenário",
  "lass_third_job": "Vingador",
  "lass_forth_job": "Retalhador",
  "ryan_first_job": "Druida",
  "ryan_second_job": "Sentinela",
  "ryan_third_job": "Xamã",
  "ryan_forth_job": "Executor",
  "ronan_first_job": "Arcano",
  "ronan_second_job": "Draconiano",
  "ronan_third_job": "Defensor",
  "ronan_forth_job": "Inquisidor",
  "amy_first_job": "Dançarina",
  "amy_second_job": "Musa",
  "amy_third_job": "Diva",
  "amy_forth_job": "Superstar",
  "jin_first_job": "Lutador",
  "jin_second_job": "Mestre",
  "jin_third_job": "Monge",
  "jin_forth_job": "Iluminado",
  "sieghart_first_job": "Gladiador",
  "sieghart_second_job": "Comandante",
  "sieghart_third_job": "General",
  "sieghart_forth_job": "Avatar",
  "mari_first_job": "Tecnomaga",
  "mari_second_job": "Duelista",
  "mari_third_job": "Polaris",
  "mari_forth_job": "La Geas",
  "dio_first_job": "Profrano",
  "dio_second_job": "Drakar",
  "dio_third_job": "Leviatã",
  "dio_forth_job": "Asmodeus",
  "zero_first_job": "Andarilho",
  "zero_second_job": "Peregrino",
  "zero_third_job": "Errante",
  "zero_forth_job": "Insurgente",
  "rey_first_job": "Invocadora",
  "rey_second_job": "Encantrix",
  "rey_third_job": "Princesa de Elyos",
  "rey_forth_job": "Imperatriz das trevas",
  "lupus_first_job": "Caçador de recompensas",
  "lupus_second_job": "Rastreador",
  "lupus_third_job": "Justiceiro",
  "lupus_forth_job": "Especialista",
  "lin_first_job": "Sacerdotisa",
  "lin_second_job": "Despertada",
  "lin_third_job": "Caótica",
  "lin_forth_job": "Escolhida",
  "azin_first_job": "Guerreiro",
  "azin_second_job": "Ryujin",
  "holy_first_job": "Paladina",
  "holy_second_job": "Templária",
  "edel_first_job": "Capitã",
  "edel_second_job": "Major",
  "veigas_first_job": "Destruidor",
  "decane_first_job": "Bruxa do Caos",
  "decane_second_job": "Bruxa Lunática",
  "ai_first_job": "Operadora",
  "ai_second_job": "Supervisora",
  "kallia_first_job": "Investigadora",
  "kallia_second_job": "Solucionadora",
  "uno_first_job": "Sanguinário",
  "uno_second_job": "Sombra Sangrenta",
}